export enum TimeRangeRelationship{
    GAP_BEFORE = 'GAP_BEFORE',
    IMMEDIATELY_BEFORE = 'IMMEDIATELY_BEFORE',
    OVERLAPS = 'OVERLAPS',
    IMMEDIATELY_AFTER = 'IMMEDIATELY_AFTER',
    GAP_AFTER = 'GAP_AFTER'
}  