export enum SleepProfileActions{
    WAKEUP_TIME = 'WAKEUP_TIME', 
    PREV_FALL_ASLEEP_TIME = 'PREV_FALL_ASLEEP_TIME',
    SLEEP_DURATION =  'SLEEP_DURATION',
    ENERGY_WAKEUP = 'ENERGY_WAKEUP',
    BEDTIME = 'BEDTIME',
    // ENERGY_PRESENT = 'ENERGY_PRESENT',
    DREAMS = 'DREAMS',
}