export enum MenuItemType{
    USER_ACCOUNT = 'USER_ACCOUNT',
    DAYBOOK = 'DAYBOOK',
    NOTES = 'NOTES',
    TASKS = 'TASKS',
    ACTIVITIES = 'ACTIVITIES',
    SETTINGS = 'SETTINGS',
    LOGOUT = 'LOGOUT',
}