export enum SleepCyclePosition {
    ACTIVE = 'ACTIVE',
    BEFORE_BEDTIME = 'BEFORE_BEDTIME',
    AFTER_BEDTIME = 'AFTER_BEDTIME',
    SLEEP = 'SLEEP',
    EARLY_WAKEUP = 'EARLY_WAKEUP',
    NEXT_DAY = 'NEXT_DAY',
}