export enum TLEFFormCase{
    NEW_CURRENT = 'NEW_CURRENT',
    NEW_CURRENT_FUTURE = 'NEW_CURRENT_FUTURE',
    NEW_PREVIOUS = 'NEW_PREVIOUS',
    NEW_FUTURE = 'NEW_FUTURE',
    EXISTING_FUTURE = 'EXISTING_FUTURE',
    EXISTING_PREVIOUS = 'EXISTING_PREVIOUS',
}