
export enum ToolType {
    NOTEBOOK_ENTRY = "NOTEBOOK_ENTRY",
    ACTION_ITEM = "ACTION_ITEM",
    TIMELOG_ENTRY = "TIMELOG_ENTRY",
    DAYBOOK_ENTRY = "DAYBOOK_ENTRY",
    FUTURE_EVENT = "FUTURE_EVENT",
    DAILY_TASK_LIST = "DAILY_TASK_LIST",
    SLEEP_ENTRY = 'SLEEP_ENTRY',
    START_NEW_DAY = 'START_NEW_DAY'
}